version: '3'
services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: dev_password
      POSTGRES_DB: dev_fmt
    ports:
      - "5432:5432"
    networks:
      - fmt_network
  fmtbe:
    build:
      context: .
      target: fmtbe
    container_name: fmtbe
    ports:
      - "8080:8080"
    networks:
      - fmt_network
    depends_on:
      - postgres
  migration:
    build:
      context: .
      target: migrations
    command:
      [
        "./wait-for-it/wait-for-it.sh",
        "postgres:5432",
        "--",
        "npm",
        "run",
        "migrate"
      ]
    links:
      - postgres
    depends_on:
      - postgres
    env_file: ./.env
    environment:
      - DB_HOST=postgres
    networks:
      - fmt_network
networks:
  fmt_network: